export var FactionNames;
(function (FactionNames) {
    FactionNames["Illuminati"] = "Illuminati";
    FactionNames["Daedalus"] = "Daedalus";
    FactionNames["TheCovenant"] = "The Covenant";
    FactionNames["ECorp"] = "ECorp";
    FactionNames["MegaCorp"] = "MegaCorp";
    FactionNames["BachmanAssociates"] = "Bachman & Associates";
    FactionNames["BladeIndustries"] = "Blade Industries";
    FactionNames["NWO"] = "NWO";
    FactionNames["ClarkeIncorporated"] = "Clarke Incorporated";
    FactionNames["OmniTekIncorporated"] = "OmniTek Incorporated";
    FactionNames["FourSigma"] = "Four Sigma";
    FactionNames["KuaiGongInternational"] = "KuaiGong International";
    FactionNames["FulcrumSecretTechnologies"] = "Fulcrum Secret Technologies";
    FactionNames["BitRunners"] = "BitRunners";
    FactionNames["TheBlackHand"] = "The Black Hand";
    FactionNames["NiteSec"] = "NiteSec";
    FactionNames["Aevum"] = "Aevum";
    FactionNames["Chongqing"] = "Chongqing";
    FactionNames["Ishima"] = "Ishima";
    FactionNames["NewTokyo"] = "New Tokyo";
    FactionNames["Sector12"] = "Sector-12";
    FactionNames["Volhaven"] = "Volhaven";
    FactionNames["SpeakersForTheDead"] = "Speakers for the Dead";
    FactionNames["TheDarkArmy"] = "The Dark Army";
    FactionNames["TheSyndicate"] = "The Syndicate";
    FactionNames["Silhouette"] = "Silhouette";
    FactionNames["Tetrads"] = "Tetrads";
    FactionNames["SlumSnakes"] = "Slum Snakes";
    FactionNames["Netburners"] = "Netburners";
    FactionNames["TianDiHui"] = "Tian Di Hui";
    FactionNames["CyberSec"] = "CyberSec";
    FactionNames["Bladeburners"] = "Bladeburners";
    FactionNames["ChurchOfTheMachineGod"] = "Church of the Machine God";
    FactionNames["ShadowsOfAnarchy"] = "Shadows of Anarchy";
})(FactionNames || (FactionNames = {}));
export var FactionType;
(function (FactionType) {
    FactionType[FactionType["Criminal"] = 0] = "Criminal";
    FactionType[FactionType["Corporation"] = 1] = "Corporation";
    FactionType[FactionType["Hacking"] = 2] = "Hacking";
    FactionType[FactionType["City"] = 3] = "City";
    FactionType[FactionType["Endgame"] = 4] = "Endgame";
    FactionType[FactionType["Special"] = 5] = "Special";
})(FactionType || (FactionType = {}));
export const Factions = new Map();
